import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  ArrowLeft, ShieldCheck, Search, Globe, CheckCircle2, 
  Trash2, Link, Bot, UserCheck, Sparkles, RefreshCcw, Copy, Check
} from 'lucide-react';

export default function PlagiarismCheckerView({ showToast }) {
  const navigate = useNavigate();
  const [text, setText] = useState('');
  const [humanizedText, setHumanizedText] = useState(null);
  const [status, setStatus] = useState('idle'); // idle, scanning, humanizing, done
  const [results, setResults] = useState(null);
  const [copied, setCopied] = useState(false);

  // --- DETERMINISTIC HASH FUNCTION ---
  const calculateHash = (str) => {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = (hash << 5) - hash + str.charCodeAt(i);
      hash |= 0; 
    }
    return Math.abs(hash);
  };

  // --- SMART API SIMULATION: SCAN ---
  const runPlagiarismScan = () => {
    if (!text.trim()) {
      if (showToast) showToast("Please enter text to scan.");
      return;
    }
    const words = text.trim().split(/\s+/);
    if (words.length < 15) {
      if (showToast) showToast("Please enter at least 15 words for an accurate scan.");
      return;
    }

    setStatus('scanning');
    setResults(null);
    setHumanizedText(null);

    setTimeout(() => {
      const lowerText = text.toLowerCase();
      const textHash = calculateHash(lowerText);
      
      // Check for our invisible watermark generated by the Humanizer
      const isHumanizedByUs = text.includes('\u200B');

      let calculatedHumanScore;
      let calculatedUniqueScore;
      let generatedMatches = [];

      if (isHumanizedByUs) {
        // Watermark found: Guarantee perfect scores
        calculatedHumanScore = 96 + (textHash % 4); // 96% to 99%
        calculatedUniqueScore = 100;
        generatedMatches = [];
      } else {
        // Raw text: Check for AI buzzwords to penalize further
        const aiFootprints = [
          "digital landscape", "digital age", "furthermore", "moreover", 
          "in conclusion", "ultimately", "utilize", "delve", "tapestry", 
          "myriad", "symphony", "testament", "seamlessly", "foster", 
          "elevate", "synergy", "navigate", "undeniable", "revolutionize",
          "crucial", "fast-paced", "realm", "dynamic", "pivotal", "intricate"
        ];
        
        let footprintCount = 0;
        aiFootprints.forEach(word => {
          if (lowerText.includes(word)) footprintCount++;
        });

        if (footprintCount > 0) {
          // Heavy AI Footprints detected: Score very low
          calculatedHumanScore = Math.max(12, 65 - (footprintCount * 8) - (textHash % 10));
          calculatedUniqueScore = 40 + (textHash % 40);
        } else {
          // Generic Text: Base it on hash (35% to 75% Human) to force demo usage
          calculatedHumanScore = 35 + (textHash % 40); 
          calculatedUniqueScore = 50 + (textHash % 30);
        }

        // Generate fake matches for raw text
        generatedMatches.push({
          id: 1,
          url: textHash % 2 === 0 ? "https://example-article-source.com/blog/content" : "https://medium.com/tech-insights",
          matchedText: words.slice(0, Math.min(12, words.length)).join(" ") + "...",
          similarity: (60 + (textHash % 30)) + "%"
        });

        if (textHash % 3 === 0) {
          generatedMatches.push({
            id: 2,
            url: "https://wikipedia.org/wiki/Contextual_Data",
            matchedText: words.slice(Math.floor(words.length / 2), Math.floor(words.length / 2) + 12).join(" ") + "...",
            similarity: (40 + (textHash % 20)) + "%"
          });
        }
      }

      setResults({
        uniqueScore: calculatedUniqueScore,
        plagiarizedScore: 100 - calculatedUniqueScore,
        humanScore: calculatedHumanScore,
        matches: generatedMatches
      });

      setStatus('done');
      if (showToast) showToast("Scan complete!");
    }, 2000);
  };

  // --- API SIMULATION: HUMANIZE TEXT & WATERMARK ---
  const humanizeText = () => {
    if (!text.trim()) return;
    
    setStatus('humanizing');

    setTimeout(() => {
      // Scrub AI footprints
      let humanized = text
        .replace(/In today's fast-paced digital landscape,?/gi, "These days,")
        .replace(/In today's digital age,?/gi, "Today,")
        .replace(/digital landscape/gi, "modern world")
        .replace(/digital age/gi, "modern times")
        .replace(/It is important to note that/gi, "Keep in mind that")
        .replace(/It goes without saying that/gi, "Obviously,")
        .replace(/Furthermore,/gi, "Plus,")
        .replace(/Moreover,/gi, "Also,")
        .replace(/In conclusion,/gi, "To sum it up,")
        .replace(/Ultimately,/gi, "In the end,")
        .replace(/utilize/gi, "use")
        .replace(/delve/gi, "look")
        .replace(/crucial/gi, "key")
        .replace(/intricate tapestry/gi, "complex mix")
        .replace(/tapestry/gi, "mix")
        .replace(/a myriad of/gi, "a lot of")
        .replace(/myriad/gi, "many")
        .replace(/a symphony of/gi, "a great combination of")
        .replace(/symphony/gi, "harmony")
        .replace(/testament/gi, "proof")
        .replace(/seamlessly/gi, "smoothly")
        .replace(/foster/gi, "build")
        .replace(/elevate/gi, "boost")
        .replace(/synergy/gi, "teamwork")
        .replace(/navigate/gi, "handle")
        .replace(/undeniable/gi, "clear")
        .replace(/revolutionize/gi, "change")
        .replace(/realm/gi, "area")
        .replace(/fast-paced/gi, "quick");

      // INJECT INVISIBLE WATERMARK (\u200B) TO GUARANTEE 100% SCORE ON RESCAN
      humanized += '\u200B';

      setHumanizedText(humanized);
      
      const newHash = calculateHash(humanized.toLowerCase());

      setResults({
        uniqueScore: 100,
        plagiarizedScore: 0,
        humanScore: 96 + (newHash % 4), // 96% to 99%
        matches: []
      });

      setStatus('done');
      if (showToast) showToast("AI footprints removed! Text is now highly humanized.");
    }, 2500);
  };

  const copyHumanized = () => {
    if (humanizedText) {
      navigator.clipboard.writeText(humanizedText);
      setCopied(true);
      if (showToast) showToast("Humanized text copied!");
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const clearAll = () => {
    setText('');
    setHumanizedText(null);
    setStatus('idle');
    setResults(null);
  };

  const gridContainerClass = humanizedText 
    ? "grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1 pb-8" 
    : "grid grid-cols-1 lg:grid-cols-12 gap-6 flex-1 pb-8"; 

  const leftColumnClass = humanizedText
    ? "lg:col-span-1 flex flex-col gap-6"
    : "lg:col-span-7 flex flex-col gap-6";

  const rightColumnClass = humanizedText
    ? "lg:col-span-1 flex flex-col gap-6"
    : "lg:col-span-5 flex flex-col gap-6";

  return (
    <div className={`w-full px-4 sm:px-8 pt-4 animate-fade-in-up mx-auto flex flex-col min-h-[calc(100vh-120px)] transition-all duration-500 ${humanizedText ? 'max-w-[1600px]' : 'max-w-[1200px]'}`}>
      
      {/* Header */}
      <div className="relative flex items-center justify-center mb-8 shrink-0">
        <button onClick={() => navigate('/')} className="absolute left-0 group flex items-center gap-2 text-gray-400 hover:text-white transition-colors text-xs font-semibold tracking-wide uppercase">
          <div className="p-1.5 rounded-full bg-white/[0.03] group-hover:bg-white/[0.08] transition-all duration-300 border border-white/[0.05]">
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
          </div>
          <span className="hidden sm:block">Back</span>
        </button>
        <div className="text-center">
            <h1 className="text-2xl sm:text-3xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-green-500 tracking-tight flex items-center justify-center gap-3">
              Originality Suite <ShieldCheck className="w-6 h-6 text-emerald-400" />
            </h1>
            <p className="text-gray-500 text-[10px] sm:text-[11px] uppercase tracking-widest mt-1 hidden sm:block">
              Plagiarism Scanner & AI Footprint Remover
            </p>
        </div>
      </div>

      <div className={gridContainerClass}>
        
        {/* Column 1: Original Input */}
        <div className={leftColumnClass}>
          <div className="bg-[#050505]/80 backdrop-blur-3xl rounded-[2rem] p-6 border border-white/[0.05] shadow-2xl flex-1 flex flex-col relative transition-all">
            
            {text.length > 0 && status === 'idle' && (
              <button 
                onClick={clearAll}
                className="absolute top-6 right-6 p-2 text-gray-500 hover:text-rose-400 hover:bg-rose-500/10 rounded-lg transition-colors z-10"
                title="Clear Text"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            )}

            <div className="flex justify-between items-center mb-4">
              <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest">
                {humanizedText ? "Original Content" : "Your Content"}
              </label>
              <span className="text-[10px] font-mono text-gray-500 mr-8">{text.trim().split(/\s+/).filter(w=>w).length} Words</span>
            </div>
            
            <textarea 
              value={text}
              onChange={(e) => setText(e.target.value)}
              disabled={status === 'scanning' || status === 'humanizing'}
              placeholder="Paste your article or essay here. We will scan billions of web pages for plagiarism and check for AI footprints..."
              className="w-full flex-1 bg-black/40 border border-white/[0.05] rounded-xl p-4 text-sm text-white placeholder-gray-600 focus:outline-none focus:border-emerald-500/50 shadow-inner resize-none min-h-[300px] custom-scrollbar disabled:opacity-50"
            />
            
            <div className={`grid gap-4 mt-4 ${humanizedText ? 'grid-cols-1' : 'grid-cols-1 sm:grid-cols-2'}`}>
              <button 
                onClick={runPlagiarismScan}
                disabled={status === 'scanning' || status === 'humanizing' || !text.trim()}
                className="w-full bg-gradient-to-r from-emerald-600 to-green-500 hover:from-emerald-500 hover:to-green-400 disabled:opacity-50 disabled:grayscale text-white font-extrabold text-[11px] uppercase tracking-widest px-6 py-4 rounded-xl transition-all shadow-[0_0_20px_rgba(16,185,129,0.2)] active:scale-95 flex items-center justify-center gap-2"
              >
                {status === 'scanning' ? (
                  <><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div> Scanning...</>
                ) : (
                  <><Search className="w-4 h-4" /> Scan Content</>
                )}
              </button>

              <button 
                onClick={humanizeText}
                disabled={status === 'scanning' || status === 'humanizing' || !text.trim() || humanizedText}
                className="w-full bg-gradient-to-r from-violet-600 to-fuchsia-500 hover:from-violet-500 hover:to-fuchsia-400 disabled:opacity-50 disabled:grayscale text-white font-extrabold text-[11px] uppercase tracking-widest px-6 py-4 rounded-xl transition-all shadow-[0_0_20px_rgba(139,92,246,0.2)] active:scale-95 flex items-center justify-center gap-2"
              >
                {status === 'humanizing' ? (
                  <><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></div> Rewriting...</>
                ) : (
                  <><Sparkles className="w-4 h-4" /> Humanize AI Text</>
                )}
              </button>
            </div>
          </div>
        </div>

        {/* Column 2: Humanized Output (Conditionally Rendered) */}
        {humanizedText && (
          <div className="lg:col-span-1 flex flex-col gap-6 animate-fade-in-up">
            <div className="bg-[#050505]/80 backdrop-blur-3xl rounded-[2rem] p-6 border border-fuchsia-500/20 shadow-[0_0_40px_rgba(139,92,246,0.1)] flex-1 flex flex-col relative transition-all">
              
              <button 
                onClick={copyHumanized}
                className="absolute top-6 right-6 p-2 text-fuchsia-400 hover:text-white hover:bg-fuchsia-500/20 bg-fuchsia-500/10 rounded-lg transition-colors z-10"
                title="Copy Humanized Text"
              >
                {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </button>

              <div className="flex justify-between items-center mb-4">
                <label className="block text-xs font-bold text-fuchsia-400 uppercase tracking-widest flex items-center gap-2">
                  <Sparkles className="w-3.5 h-3.5" /> Humanized Content
                </label>
                <span className="text-[10px] font-mono text-gray-500 mr-8">{humanizedText.trim().split(/\s+/).filter(w=>w).length} Words</span>
              </div>
              
              <textarea 
                value={humanizedText}
                onChange={(e) => setHumanizedText(e.target.value)}
                placeholder="Your humanized text will appear here..."
                className="w-full flex-1 bg-black/40 border border-fuchsia-500/20 rounded-xl p-4 text-sm text-gray-200 focus:outline-none focus:border-fuchsia-500/50 shadow-inner resize-none min-h-[300px] custom-scrollbar"
              />

              <div className="mt-4 flex items-center justify-center p-3 rounded-xl bg-fuchsia-500/10 border border-fuchsia-500/20 text-fuchsia-400 text-[10px] uppercase tracking-widest font-bold">
                <CheckCircle2 className="w-4 h-4 mr-2" /> AI Footprints Removed (&gt;95% Human)
              </div>
            </div>
          </div>
        )}

        {/* Column 3: Results Report */}
        <div className={rightColumnClass}>
          <div className="bg-[#050505]/80 backdrop-blur-3xl rounded-[2rem] p-6 border border-white/[0.05] shadow-2xl flex-1 flex flex-col transition-all">
            <label className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">Analysis Report</label>
            
            {status === 'idle' ? (
              <div className="flex-1 border border-white/5 border-dashed rounded-xl flex flex-col items-center justify-center text-gray-600 min-h-[300px]">
                <Globe className="w-12 h-12 mb-3 opacity-20" />
                <p className="text-xs text-center px-6">Your detailed originality report, AI detection score, and matched sources will appear here.</p>
              </div>
            ) : status === 'scanning' ? (
              <div className="flex-1 border border-emerald-500/20 border-dashed rounded-xl flex flex-col items-center justify-center text-emerald-500 min-h-[300px] bg-emerald-500/5">
                <Globe className="w-12 h-12 mb-4 animate-pulse" />
                <p className="text-xs font-bold tracking-widest uppercase animate-pulse text-center px-4">Checking billions of pages...</p>
              </div>
            ) : status === 'humanizing' ? (
              <div className="flex-1 border border-fuchsia-500/20 border-dashed rounded-xl flex flex-col items-center justify-center text-fuchsia-400 min-h-[300px] bg-fuchsia-500/5">
                <RefreshCcw className="w-12 h-12 mb-4 animate-spin" />
                <p className="text-xs font-bold tracking-widest uppercase animate-pulse text-center px-4">Scrubbing AI Footprints...</p>
                <p className="text-[10px] text-fuchsia-500/70 mt-2 text-center px-4">Adjusting perplexity and burstiness metrics</p>
              </div>
            ) : (
              <div className="flex flex-col gap-6 animate-fade-in-up h-full">
                
                {/* Score Visualizers */}
                <div className={`grid gap-3 ${humanizedText ? 'grid-cols-1' : 'grid-cols-2'}`}>
                  
                  {/* Plagiarism Score */}
                  <div className="flex flex-col items-center justify-center p-4 border border-white/5 rounded-2xl bg-black/40">
                    <span className={`text-3xl font-black mb-1 ${results.plagiarizedScore > 0 ? 'text-rose-500' : 'text-emerald-400'}`}>
                      {results.uniqueScore}%
                    </span>
                    <span className="text-[9px] font-bold text-gray-500 uppercase tracking-widest flex items-center gap-1">
                      <ShieldCheck className="w-3 h-3" /> Unique Content
                    </span>
                  </div>

                  {/* AI Detection Score */}
                  <div className={`flex flex-col items-center justify-center p-4 border rounded-2xl bg-black/40 ${humanizedText ? 'border-fuchsia-500/30 shadow-[0_0_15px_rgba(139,92,246,0.1)]' : 'border-white/5'}`}>
                    <span className={`text-3xl font-black mb-1 ${results.humanScore > 90 ? 'text-violet-400' : 'text-amber-500'}`}>
                      {results.humanScore}%
                    </span>
                    <span className="text-[9px] font-bold text-gray-500 uppercase tracking-widest flex items-center gap-1">
                      {results.humanScore > 90 ? <UserCheck className="w-3 h-3" /> : <Bot className="w-3 h-3" />} 
                      Human Written
                    </span>
                  </div>

                </div>

                {/* AI Warning Context (Hidden if Humanized) */}
                {results.humanScore < 90 && !humanizedText && (
                  <div className="bg-amber-500/10 border border-amber-500/20 rounded-xl p-3 flex gap-3 items-start">
                    <Bot className="w-4 h-4 shrink-0 text-amber-500 mt-0.5" />
                    <div>
                      <h4 className="text-xs font-bold text-amber-500">AI Content Detected</h4>
                      <p className="text-[10px] text-amber-500/80 mt-1">This text shows footprints of AI generation (low perplexity). Use the <b>Humanize AI Text</b> button to rewrite it and bypass detectors.</p>
                    </div>
                  </div>
                )}

                {/* Match List */}
                <div className="flex-1 flex flex-col min-h-0 mt-2">
                  <h3 className="text-[10px] font-bold text-gray-500 uppercase tracking-widest mb-3">Plagiarism Sources ({results.matches.length})</h3>
                  
                  {results.matches.length === 0 ? (
                    <div className="flex-1 bg-emerald-500/10 border border-emerald-500/20 rounded-xl p-6 flex flex-col items-center justify-center text-center">
                      <CheckCircle2 className="w-10 h-10 text-emerald-400 mb-3" />
                      <h4 className="text-sm font-bold text-emerald-400 mb-1">100% Original Content</h4>
                      <p className="text-[10px] sm:text-xs text-emerald-500/70">We couldn't find any matching text on the internet.</p>
                    </div>
                  ) : (
                    <div className="space-y-3 overflow-y-auto custom-scrollbar pr-2 flex-1">
                      {results.matches.map((match) => (
                        <div key={match.id} className="p-4 rounded-xl border border-rose-500/20 bg-rose-500/5 flex flex-col gap-2">
                          <div className="flex items-start justify-between gap-2">
                            <span className="text-[10px] sm:text-xs font-bold text-rose-400 flex items-center gap-1.5 break-all">
                              <Link className="w-3 h-3 shrink-0" /> {match.url}
                            </span>
                            <span className="bg-rose-500/20 text-rose-400 text-[9px] font-bold px-2 py-0.5 rounded-full shrink-0">
                              {match.similarity} Match
                            </span>
                          </div>
                          <p className="text-[10px] sm:text-[11px] text-gray-400 leading-relaxed bg-black/40 p-2 rounded border border-white/5 font-serif italic">
                            "{match.matchedText}"
                          </p>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

              </div>
            )}
          </div>
        </div>

      </div>
    </div>
  );
}